name: model-server-basaran
run-name: ${{ github.actor }} triggered Docker pipeline for ${{ github.workflow }} 🚀
on:
  push:
    paths:
      - "model-server-basaran/*"
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
jobs:
  docker-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # GITHUB_WORKFLOW is the same as workflow name
          images: substratusai/${{ github.workflow }}
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: ./${{ github.workflow }}
          platforms: "linux/amd64"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
