name: model-trainer-huggingface
run-name: ${{ github.actor }} triggered Docker pipeline for ${{ github.workflow }} 🚀
on:
  push:
    paths:
      - 'model-trainer-huggingface/*'
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
jobs:
  base:
    uses: ./.github/workflows/base.yaml
  docker-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: substratusai/model-trainer-huggingface
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: ./model-trainer-huggingface
          platforms: "linux/amd64"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
